### ISSUE TITLE
cara clone gitlab

### ISSUE THREAD

**Issue by alimbahriii** [ferdhika31/ppid#2]
bang gimana cara clone git labnya dong?

**Comment by ferdhika31** [comment]
oh iya mas @alimbahriii, mohon maaf untuk projectnya ini private mas.. jadi ga ada public reponya.. maaf baru bales juga

**Comment by alimbahriii** [comment]
Saya boleh minta source codenya yg mentah gak bang? Saya hanya ingin
mengetahui fungsionalitas dan fitur2 dlm aplikasi ppid, Saya akan mengubah
tampilannya agak tidak identik dan menghargai project sebelumnya

Pada tanggal Sen, 30 Agu 2021 17:25, Ferdhika Yudira <
***@***.***> menulis:
